name: Run tests & deploy

on: push

env:
  secrets_private_key: ${{ secrets.SHH_PRIVATE_KEY }}
  secrets_host: ${{ secrets.SSH_HOST }}
  secrets_user: ${{ secrets.SSH_USER }}
  secrets_port: ${{ secrets.SSH_PORT }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          key: secrets_private_key
      - name: Adding Know Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts      
      - name: Deploy with digitalocean
        run: rsync -avz ./Continuous_Deployment/ secrets_user@secrets_host:/home/cd



