name: Run tests & deploy

on: push

env:
  secrets_private_key: ${{ secrets.SHH_PRIVATE_KEY }}
  secrets_host: ${{ secrets.SSH_HOST }}
  secrets_user: ${{ secrets.SSH_USER }}
  secrets_port: ${{ secrets.SSH_PORT }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          key: -----BEGIN OPENSSH PRIVATE KEY-----
               b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
               NhAAAAAwEAAQAAAgEA21Ijn9p2H3rNKHcSFyEgEr5uH58rCEjlfO8dy7PNUIAt9SC8ORdA
               OslYszjTPfcTncJL97Asd9jZCMPsuOBlCijPFVhKhWSoqCi/FFJRii+rhzWx9wnA3/IeHN
               MvzpYJMhjCOmnMaKw6R/H+64MhwayOetkGtVx04vSaoc3RinM88UvZ5pIrg5y1/yWDxHvg
               51kBFPcCcxBjMJ4K4yue/J/DVDDkYFP+tlS5ggw7V34o4oNFwH3e/zB4oc5Nkdnp66r0aU
               IU/X015dLceobko+kEfPkKVZNkKqdwncT6bzguXqOX8r+e8nKsEa0CC0S3VcsfiR1Va+MP
               dlzSFfQhd+yEc5faA4IOC/SGEafjm7TlJaAcbBXF5CoOZCRObZR5S7j8W9pLghHSpTngLz
               YP6OAbkIowbGkAEwfDK5R6CL81DfoetAcWwrPM25O6cZfxdwEMrzPOUavTIXu8JIpdSaWW
               /MPpoSO6dw8wUy9Y2GhmYChWEo/VJUPrPg9cUBm9/ykt1VdkS8vHke7Ytze2OhxwTYLuOW
               mZgIKk6QoI+i24uOuKC+HjZiIMsgrRX2mcua6wzQAfDYDddjErA62i2KNNb5Pi2yVt3EuO
               ZFnVShjFaEw0hsgM0RjZqLTHyKO2KC6Wd88XzlPCQhEGepA2HijYH/DFLRcOWcYIpLeiJ9
               8AAAdIlftBP5X7QT8AAAAHc3NoLXJzYQAAAgEA21Ijn9p2H3rNKHcSFyEgEr5uH58rCEjl
               fO8dy7PNUIAt9SC8ORdAOslYszjTPfcTncJL97Asd9jZCMPsuOBlCijPFVhKhWSoqCi/FF
               JRii+rhzWx9wnA3/IeHNMvzpYJMhjCOmnMaKw6R/H+64MhwayOetkGtVx04vSaoc3RinM8
               8UvZ5pIrg5y1/yWDxHvg51kBFPcCcxBjMJ4K4yue/J/DVDDkYFP+tlS5ggw7V34o4oNFwH
               3e/zB4oc5Nkdnp66r0aUIU/X015dLceobko+kEfPkKVZNkKqdwncT6bzguXqOX8r+e8nKs
               Ea0CC0S3VcsfiR1Va+MPdlzSFfQhd+yEc5faA4IOC/SGEafjm7TlJaAcbBXF5CoOZCRObZ
               R5S7j8W9pLghHSpTngLzYP6OAbkIowbGkAEwfDK5R6CL81DfoetAcWwrPM25O6cZfxdwEM
               rzPOUavTIXu8JIpdSaWW/MPpoSO6dw8wUy9Y2GhmYChWEo/VJUPrPg9cUBm9/ykt1VdkS8
               vHke7Ytze2OhxwTYLuOWmZgIKk6QoI+i24uOuKC+HjZiIMsgrRX2mcua6wzQAfDYDddjEr
               A62i2KNNb5Pi2yVt3EuOZFnVShjFaEw0hsgM0RjZqLTHyKO2KC6Wd88XzlPCQhEGepA2Hi
               jYH/DFLRcOWcYIpLeiJ98AAAADAQABAAACAB46pxBcYxWZrndaWhL4DNyohLM1FBBTQ9ZB
               ewDdqnnjAPKdbXQNAVxY7jHdrjgHOxvucNwV2zs1l0x+/LzKqQKKd2iAv9y88AYlf5jEc9
               qxEVpUi0/6dywmygG9FgTKZ0ARa4vzkyoGOw45i6JYc6mnKAhEq4kJ0k6J2lpc7PnBQnAb
               vU/ra7X7PpaJTC0jye75NI34Mc08P/+ueN+w3nwBZUHQb1nbmer1qJAFMZSwneACqfWLI9
               ZWjvn2Xniw6W4DJSbw5cW+oVQpCRyWRSNWdbjn9oWvCApdA8erI716p+GBeOsLgFP4fED/
               cJ2u/foEQjd65JA3PqVYy9gcyxPkAdHk5bwsc00QwhuC6DF2Wewqldkb6cJ9Bm+MW9ufaH
               bwCKgQZ1bT8I99GkdbT/wLVj815h6289I/ejd0IHxCaMUGTlWiMC+BGQaGC6hE0j6RdaDj
               hWpK0MAzX+bFySLUTPjv9Qtl//fbSCt8fVCwNYZI8FXi3xfHBRN0XfpCtur6AFfBji6O3H
               cFPWsILckLµS9XueTo/+GZKCw20NWu/e/O4SeJxIVof/5Fk/AJaI80Kz4ac+Axg9OWaCNEB
               SOlNSC4SyC/ITMOBKqnP5oIiYmMK8av2lW6ir03YzpQ7XrZ/mjsJ3STRMlzdd7pREHKljD
               QZ83NtMG6rFXLzJYiZAAABAGjub7NCgZlWmoRi6yotZ8tdimrMpUlvVGkYURhQrkDBcyfX
               6AYsnhFrtJci1Zyw07PSloCoZUIzdi7vad+pg9fwe38cIj+20s5MQntoh8VAwuwZcIaL7/
               db6tpL5hWGIK5T0apgEMAAcC9gKPvoRF1RLDtFJSdAK1IXbJosvMzx3GZ13jha8zXVaEb0
               hYTgAETl8D6Fc8j+0J/7uvTPFzi7jIArRKTpHhyq6BqBnZP5C3v0UUGt5n4QIm4LFMLjK4
               D6fBIA9K8hloYJshuJ7hWtAEOOPyzfElQ3CcXqF+wPqa51Ge99DdFW3TdZrjLAvGim9Q65
               rU4C9BLxV3zCX+cAAAEBAN6CGBA9FZZB+7Ggzmsi4IwgpXL0qnufT4bCg/s73euewQYqcr
               RZmr80GnTGohLkqRBw9E8sxrOOaTieC+vuszEiwBTgygNYrox7h7nuoY5hdpUSRidhXuYl
               JEjaet5/5TE2Qk3iASS+hvs1OSy5lEIF9xqnTwbfQpRrSxi8Jrns1RuHMnmzbjcx6lXbke
               Ssj34d2hwzS2oCo4Q+q1+6YuPC8U3js2hOCZwT8a7bdG6h2lEf1OJ/P0qlE4DGS/fxTD3c
               gLZ27MHgL+2EWqh9Soe+FUWRnWq6RleznBbmAhHR1PjWH15Hzxlhsqv8DiUkeujjyVUFUN
               DyrpfpxdqzQf0AAAEBAPxVOmEb1hTZXnN+okqBonWPO/JDZZ2VaLdV1dJsivnR8d9MOcZ7
               jAetCk/VUpjxSGOnBhtKtTzBPONWsXXuCIdE2fsGidcjvrLoenLUcpXG4t76fEmaqrlZrO
               9QlVwsgHFSm6gqKXmEqBYFSEzLgDBKLWluhVJZUGN3YHVornEZhsHqfYQbtMTRy/BD54Zs
               oBLOGBRPua0ZlzwzSrHJDTdvEklKjuqrAaAU/uthbqyy96oR0lLivGnvFMEov3jgjHnN6I
               SJ0IERmqDOA2Kay8NYvAvqchmw0yIErWrxIpfRDqUxqTyh5V8vukdZ9AFWSWHTXCFjQuB0
               YOnRC+hXOgsAAAARZmFta2VwakBnbWFpbC5jb20BAg==
               -----END OPENSSH PRIVATE KEY-----
      - name: Adding Know Hosts
        run: ssh-keyscan -H 104.248.81.86  >> ~/.ssh/known_hosts
      - name: Deploy with digitalocean
        #uses: appleboy/ssh-action@v0.1.2
        uses: appleboy/ssh-action@master
        with:
          host: 104.248.81.86
          key: -----BEGIN OPENSSH PRIVATE KEY-----
               b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
               NhAAAAAwEAAQAAAgEA21Ijn9p2H3rNKHcSFyEgEr5uH58rCEjlfO8dy7PNUIAt9SC8ORdA
               OslYszjTPfcTncJL97Asd9jZCMPsuOBlCijPFVhKhWSoqCi/FFJRii+rhzWx9wnA3/IeHN
               MvzpYJMhjCOmnMaKw6R/H+64MhwayOetkGtVx04vSaoc3RinM88UvZ5pIrg5y1/yWDxHvg
               51kBFPcCcxBjMJ4K4yue/J/DVDDkYFP+tlS5ggw7V34o4oNFwH3e/zB4oc5Nkdnp66r0aU
               IU/X015dLceobko+kEfPkKVZNkKqdwncT6bzguXqOX8r+e8nKsEa0CC0S3VcsfiR1Va+MP
               dlzSFfQhd+yEc5faA4IOC/SGEafjm7TlJaAcbBXF5CoOZCRObZR5S7j8W9pLghHSpTngLz
               YP6OAbkIowbGkAEwfDK5R6CL81DfoetAcWwrPM25O6cZfxdwEMrzPOUavTIXu8JIpdSaWW
               /MPpoSO6dw8wUy9Y2GhmYChWEo/VJUPrPg9cUBm9/ykt1VdkS8vHke7Ytze2OhxwTYLuOW
               mZgIKk6QoI+i24uOuKC+HjZiIMsgrRX2mcua6wzQAfDYDddjErA62i2KNNb5Pi2yVt3EuO
               ZFnVShjFaEw0hsgM0RjZqLTHyKO2KC6Wd88XzlPCQhEGepA2HijYH/DFLRcOWcYIpLeiJ9
               8AAAdIlftBP5X7QT8AAAAHc3NoLXJzYQAAAgEA21Ijn9p2H3rNKHcSFyEgEr5uH58rCEjl
               fO8dy7PNUIAt9SC8ORdAOslYszjTPfcTncJL97Asd9jZCMPsuOBlCijPFVhKhWSoqCi/FF
               JRii+rhzWx9wnA3/IeHNMvzpYJMhjCOmnMaKw6R/H+64MhwayOetkGtVx04vSaoc3RinM8
               8UvZ5pIrg5y1/yWDxHvg51kBFPcCcxBjMJ4K4yue/J/DVDDkYFP+tlS5ggw7V34o4oNFwH
               3e/zB4oc5Nkdnp66r0aUIU/X015dLceobko+kEfPkKVZNkKqdwncT6bzguXqOX8r+e8nKs
               Ea0CC0S3VcsfiR1Va+MPdlzSFfQhd+yEc5faA4IOC/SGEafjm7TlJaAcbBXF5CoOZCRObZ
               R5S7j8W9pLghHSpTngLzYP6OAbkIowbGkAEwfDK5R6CL81DfoetAcWwrPM25O6cZfxdwEM
               rzPOUavTIXu8JIpdSaWW/MPpoSO6dw8wUy9Y2GhmYChWEo/VJUPrPg9cUBm9/ykt1VdkS8
               vHke7Ytze2OhxwTYLuOWmZgIKk6QoI+i24uOuKC+HjZiIMsgrRX2mcua6wzQAfDYDddjEr
               A62i2KNNb5Pi2yVt3EuOZFnVShjFaEw0hsgM0RjZqLTHyKO2KC6Wd88XzlPCQhEGepA2Hi
               jYH/DFLRcOWcYIpLeiJ98AAAADAQABAAACAB46pxBcYxWZrndaWhL4DNyohLM1FBBTQ9ZB
               ewDdqnnjAPKdbXQNAVxY7jHdrjgHOxvucNwV2zs1l0x+/LzKqQKKd2iAv9y88AYlf5jEc9
               qxEVpUi0/6dywmygG9FgTKZ0ARa4vzkyoGOw45i6JYc6mnKAhEq4kJ0k6J2lpc7PnBQnAb
               vU/ra7X7PpaJTC0jye75NI34Mc08P/+ueN+w3nwBZUHQb1nbmer1qJAFMZSwneACqfWLI9
               ZWjvn2Xniw6W4DJSbw5cW+oVQpCRyWRSNWdbjn9oWvCApdA8erI716p+GBeOsLgFP4fED/
               cJ2u/foEQjd65JA3PqVYy9gcyxPkAdHk5bwsc00QwhuC6DF2Wewqldkb6cJ9Bm+MW9ufaH
               bwCKgQZ1bT8I99GkdbT/wLVj815h6289I/ejd0IHxCaMUGTlWiMC+BGQaGC6hE0j6RdaDj
               hWpK0MAzX+bFySLUTPjv9Qtl//fbSCt8fVCwNYZI8FXi3xfHBRN0XfpCtur6AFfBji6O3H
               cFPWsILckLµS9XueTo/+GZKCw20NWu/e/O4SeJxIVof/5Fk/AJaI80Kz4ac+Axg9OWaCN>
               SOlNSC4SyC/ITMOBKqnP5oIiYmMK8av2lW6ir03YzpQ7XrZ/mjsJ3STRMlzdd7pREHKljD
               QZ83NtMG6rFXLzJYiZAAABAGjub7NCgZlWmoRi6yotZ8tdimrMpUlvVGkYURhQrkDBcyfX
               6AYsnhFrtJci1Zyw07PSloCoZUIzdi7vad+pg9fwe38cIj+20s5MQntoh8VAwuwZcIaL7/
               db6tpL5hWGIK5T0apgEMAAcC9gKPvoRF1RLDtFJSdAK1IXbJosvMzx3GZ13jha8zXVaEb0
               hYTgAETl8D6Fc8j+0J/7uvTPFzi7jIArRKTpHhyq6BqBnZP5C3v0UUGt5n4QIm4LFMLjK4
               D6fBIA9K8hloYJshuJ7hWtAEOOPyzfElQ3CcXqF+wPqa51Ge99DdFW3TdZrjLAvGim9Q65
               rU4C9BLxV3zCX+cAAAEBAN6CGBA9FZZB+7Ggzmsi4IwgpXL0qnufT4bCg/s73euewQYqcr
               RZmr80GnTGohLkqRBw9E8sxrOOaTieC+vuszEiwBTgygNYrox7h7nuoY5hdpUSRidhXuYl
               JEjaet5/5TE2Qk3iASS+hvs1OSy5lEIF9xqnTwbfQpRrSxi8Jrns1RuHMnmzbjcx6lXbke
               Ssj34d2hwzS2oCo4Q+q1+6YuPC8U3js2hOCZwT8a7bdG6h2lEf1OJ/P0qlE4DGS/fxTD3c
               gLZ27MHgL+2EWqh9Soe+FUWRnWq6RleznBbmAhHR1PjWH15Hzxlhsqv8DiUkeujjyVUFUN
               DyrpfpxdqzQf0AAAEBAPxVOmEb1hTZXnN+okqBonWPO/JDZZ2VaLdV1dJsivnR8d9MOcZ7
               jAetCk/VUpjxSGOnBhtKtTzBPONWsXXuCIdE2fsGidcjvrLoenLUcpXG4t76fEmaqrlZrO
               9QlVwsgHFSm6gqKXmEqBYFSEzLgDBKLWluhVJZUGN3YHVornEZhsHqfYQbtMTRy/BD54Zs
               oBLOGBRPua0ZlzwzSrHJDTdvEklKjuqrAaAU/uthbqyy96oR0lLivGnvFMEov3jgjHnN6I
               SJ0IERmqDOA2Kay8NYvAvqchmw0yIErWrxIpfRDqUxqTyh5V8vukdZ9AFWSWHTXCFjQuB0
               YOnRC+hXOgsAAAARZmFta2VwakBnbWFpbC5jb20BAg==
               -----END OPENSSH PRIVATE KEY-----
          username: root

          script: |
            mkdir test
            cd test
            git clone git@github.com:famkepj/CD.git
            echo 'Deployment succesful to digital ocean'
        #run: rsync -avz ./Continuous_Deployment/ secrets_user@secrets_host:/home/cd
        #run: rsync -avz -e "ssh -p secrets_port" ./dist/ secrets_user@secrets_host:/var/www/famkepj.com/

