name: Run tests & deploy

on: push

env:
  secrets_private_key: ${{ secrets.SHH_PRIVATE_KEY }}
  secrets_host: ${{ secrets.SSH_HOST }}
  secrets_user: ${{ secrets.SSH_USER }}
  secrets_port: ${{ secrets.SSH_PORT }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          key: secrets_private_key
      - name: Adding Know Hosts
        run: ssh-keyscan -H 104.248.81.86  >> ~/.ssh/known_hosts
      - name: Deploy with digitalocean
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 104.248.81.86
          key: secrets_private_key
          username: root

          script: |
            mkdir test
            cd test
            git clone git@github.com:famkepj/CD.git
            echo 'Deployment succesful to digital ocean'
        #run: rsync -avz ./Continuous_Deployment/ secrets_user@secrets_host:/home/cd
        #run: rsync -avz -e "ssh -p secrets_port" ./dist/ secrets_user@secrets_host:/var/www/famkepj.com/

